included:
  - GEOSwiftMapKit
  - GEOSwiftMapKitTests
disabled_rules:
  - force_cast
  - identifier_name
  - type_name
opt_in_rules:
  - closure_spacing
  - empty_count
  - implicit_return
  - pattern_matching_keywords
  - vertical_parameter_alignment_on_call
line_length: 110
