---
os: osx
osx_image: xcode12.3
language: shell

jobs:
  include:
    - name: iOS - xcodebuild
      env: PLATFORM=iOS
           SDK=iphonesimulator14.3
           DESTINATION="platform=iOS Simulator,OS=14.3,name=iPhone 11"
           RUN_CODECOV=true
    - name: tvOS - xcodebuild
      env: PLATFORM=tvOS
           SDK=appletvsimulator14.3
           DESTINATION="platform=tvOS Simulator,OS=14.3,name=Apple TV"
    - name: macOS - xcodebuild
      env: PLATFORM=macOS
           SDK=macosx11.1
           DESTINATION="platform=OS X"

before_install: ./scripts/travis_before_install.sh
script: ./scripts/travis_script.sh
after_success: ./scripts/travis_after_success.sh
