language: objective-c

osx_image: xcode10.2

cache:
  directories:
    - Carthage

env:
  global:
    - WORKSPACE=GEOSwiftMapKit.xcworkspace
  matrix:
    - PLATFORM=iOS SCHEME=GEOSwiftMapKit-iOS SDK=iphonesimulator12.2 DESTINATION="platform=iOS Simulator,OS=12.2,name=iPhone XS" 
    - PLATFORM=tvOS SCHEME=GEOSwiftMapKit-tvOS SDK=appletvsimulator12.2 DESTINATION="platform=tvOS Simulator,OS=12.2"
    - PLATFORM=macOS SCHEME=GEOSwiftMapKit-macOS SDK=macosx10.14 DESTINATION="platform=OS X"

before_install:
  - brew install carthage swiftlint
  - gem install xcpretty
  - travis_wait 30 carthage update --cache-builds --platform "$PLATFORM" --no-use-binaries

script:
  - set -o pipefail
  - xcodebuild
    -workspace "$WORKSPACE"
    -scheme "$SCHEME"
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    ONLY_ACTIVE_ARCH=YES
    clean test | xcpretty -c;

after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^GEOSwiftMapKit$'
