---
os: osx
osx_image: xcode11.3
language: minimal

cache:
  directories:
    - Carthage

jobs:
  include:
    - name: iOS - xcodebuild
      env: PLATFORM=iOS
           SCHEME=GEOSwiftMapKit-iOS
           SDK=iphonesimulator13.2
           DESTINATION="platform=iOS Simulator,OS=13.3,name=iPhone 11"
           WORKSPACE=GEOSwiftMapKit.xcworkspace
           RUN_CODECOV=true
    - name: tvOS - xcodebuild
      env: PLATFORM=tvOS
           SCHEME=GEOSwiftMapKit-tvOS
           SDK=appletvsimulator13.2
           DESTINATION="platform=tvOS Simulator,OS=13.3,name=Apple TV"
           WORKSPACE=GEOSwiftMapKit.xcworkspace
    - name: macOS - xcodebuild
      env: PLATFORM=macOS
           SCHEME=GEOSwiftMapKit-macOS
           SDK=macosx10.15
           DESTINATION="platform=OS X"
           WORKSPACE=GEOSwiftMapKit.xcworkspace
    - name: macOS - SPM
      env: USE_SPM=true

before_install: travis_wait 30 ./scripts/travis_before_install.sh
script: ./scripts/travis_script.sh
after_success: ./scripts/travis_after_success.sh
